### ISSUE TITLE
indie project checkpoint 1

### ISSUE THREAD

**Issue by akcuster** [akcuster/plantParentHelper#1]
@pawaitemadisoncollege My checkpoint is ready for review.

**Comment by pawaitemadisoncollege** [comment]
First things first! I LOVE this project idea @akcuster! The gamification idea makes it really fun. From a really practical side, the app could also be used by house sitters/plant sitters. I have some friends who travel quite a lot (at least pre-covid), and they always leave a hand-written note (or even several!) explaining how to care for their various plants while they are gone.  An app like this could make sharing those instructions so much easier! 

I think you sized your project just right - the mvp seems right on target. 

- [ ] I _think_ there are some tasks on your project plan that are not mvp? The amount of time students have to work on the indie project during weeks 9-12 is more limited due to the team project; it might be helpful to remove any non-mvp tasks (or maybe label them as non-mvp, if you don't want to lose them). 
- [ ] I like that you left photo upload as "non-mvp".   One consideration for this version is to instead allow a user to add a link to an image hosted elsewhere. This allows for some pretty pix on the site, but you are off the hook as a a developer for having to manage the upload, sizing, etc. 
- [ ] You have a good start on screen design; as you add more, work to stay focused only on screens necessary for mvp.
- [ ] I always like to poke around ProgrammableWeb.com to look for apis that might help in student projects.  Here's one that seems to be free, and might be of use: https://trefle.io. It looks like it even provides a url to a photo of the plant that you search for!  Anyway, maybe that api will provide some inspiration.
